export { default as CategoryPage } from './Category'
export { default as IndexPage } from './IndexPage'
export { default as MyAccountPage } from './MyAccount'
export { default as SignInPage } from './SignIn'
export { default as SignUpPage } from './SignUp'